// This file was autogenerated by /home/ch/.node_libraries/.npm/nclosure/0.4.2/package/third_party/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../../../../../../workspace/git/node-template/src/deps.js', [], []);
goog.addDependency('../../../../../../../../../workspace/git/node-template/src/example.js', ['example.Example'], []);
